import type { InsertPlace } from "@shared/schema";

// Portuguese places with real geographic coordinates (longitude, latitude in WGS84/EPSG:4326).
// Includes Lisbon, Porto, and other major cities across Portugal.
export const seedPlaces: InsertPlace[] = [
  {
    name: "Tasca do Chamiço",
    kind: "tasca",
    area: "Mouraria",
    city: "Lisboa",
    address: "Rua do Chamiço 12",
    description:
      "Bairro tasca with hand-folded samosas served alongside the house vinho verde. Crisp shells, generous chouriço-spiced lentils.",
    latitude: 38.717,
    longitude: -9.134,
    mapX: 58,
    mapY: 38,
  },
  {
    name: "Café Almirante",
    kind: "café",
    area: "Príncipe Real",
    city: "Lisboa",
    address: "Praça do Príncipe Real 4",
    description:
      "Third-wave café with a samosa-of-the-week. Galão-friendly hours, peixinhos-da-horta energy on the side.",
    latitude: 38.714,
    longitude: -9.145,
    mapX: 38,
    mapY: 50,
  },
  {
    name: "Bar Travessa",
    kind: "bar",
    area: "Bairro Alto",
    city: "Lisboa",
    address: "Travessa da Queimada 27",
    description:
      "Late-night bar with a permanent beef-and-coriander samosa on the petisco menu. Pairs improbably well with super bock.",
    latitude: 38.711,
    longitude: -9.149,
    mapX: 30,
    mapY: 56,
  },
  {
    name: "Padaria Nova Estrela",
    kind: "bakery",
    area: "Estrela",
    city: "Lisboa",
    address: "Rua de São Bento 142",
    description:
      "Neighbourhood padaria that bakes vegetarian samosas every morning at 8h. Sells out before lunch.",
    latitude: 38.708,
    longitude: -9.166,
    mapX: 24,
    mapY: 70,
  },
  {
    name: "Cervejaria Marítima",
    kind: "restaurant",
    area: "Cais do Sodré",
    city: "Lisboa",
    address: "Rua Nova do Carvalho 9",
    description:
      "Seafood-led restaurant doing a tuna-and-piri-piri samosa special on Thursdays. Riverside terrace.",
    latitude: 38.706,
    longitude: -9.142,
    mapX: 42,
    mapY: 78,
  },
  {
    name: "Mercearia da Graça",
    kind: "café",
    area: "Graça",
    city: "Lisboa",
    address: "Largo da Graça 37",
    description:
      "Hilltop mercearia with samosas built on Goan recipes. Pastel-de-nata adjacent display, espresso-friendly counter.",
    latitude: 38.722,
    longitude: -9.127,
    mapX: 70,
    mapY: 30,
  },
  {
    name: "Tasco do Tejo",
    kind: "tasca",
    area: "Alfama",
    city: "Lisboa",
    address: "Beco do Carneiro 6",
    description:
      "Tile-walled tasca with a single samosa on the menu — slow-cooked pork shoulder, smoked paprika, served warm.",
    latitude: 38.71,
    longitude: -9.13,
    mapX: 78,
    mapY: 50,
  },
  {
    name: "Bar Santos",
    kind: "bar",
    area: "Santos",
    city: "Lisboa",
    address: "Rua de São Paulo 88",
    description:
      "Cocktail bar tucked behind a cinema. Crab samosa with a yuzu-mint dip; ginja-spiked nightcap optional.",
    latitude: 38.704,
    longitude: -9.156,
    mapX: 18,
    mapY: 80,
  },
  {
    name: "Café Belém",
    kind: "café",
    area: "Belém",
    city: "Lisboa",
    address: "Rua de Belém 54",
    description:
      "Tourist-adjacent café gone quietly serious about samosas — chickpea, cumin, lemon. Riverwalk takeaway window.",
    latitude: 38.697,
    longitude: -9.204,
    mapX: 6,
    mapY: 88,
  },
  {
    name: "Chefe Indiano",
    kind: "restaurant",
    area: "Anjos",
    city: "Lisboa",
    address: "Rua dos Anjos 71",
    description:
      "Family-run Indian restaurant. Original samosa benchmark — flaky, peppery potato-pea filling, tamarind on the side.",
    latitude: 38.729,
    longitude: -9.126,
    mapX: 64,
    mapY: 20,
  },
  {
    name: "O Rei da Folha",
    kind: "restaurant",
    area: "Ribeira",
    city: "Porto",
    address: "Rua de São João 45",
    description:
      "Traditional Ribeira restaurant with Goan-Portuguese fusion samosas. River views, Port wine pairings.",
    latitude: 41.14,
    longitude: -8.627,
    mapX: 50,
    mapY: 40,
  },
  {
    name: "Café Príncipe",
    kind: "café",
    area: "Livraria",
    city: "Covilhã",
    address: "Avenida General Delgado 8",
    description:
      "Mountain café with samosas inspired by local hearty recipes. Warm interior, outdoor terrace year-round.",
    latitude: 40.286,
    longitude: -7.497,
    mapX: 45,
    mapY: 55,
  },
  {
    name: "Tasca Bairrada",
    kind: "tasca",
    area: "Centro Velho",
    city: "Aveiro",
    address: "Rua Direita 23",
    description:
      "Lagoon-side tasca with samosas filled with fresh fish. Casual vibe, painted tilework, espresso strong.",
    latitude: 40.643,
    longitude: -8.655,
    mapX: 48,
    mapY: 42,
  },
  {
    name: "Restaurante da Sorte",
    kind: "restaurant",
    area: "Centro",
    city: "Évora",
    address: "Largo do Conde de Vila Flor 2",
    description:
      "UNESCO-listed courtyard restaurant. Alentejo-style samosas with coriander and wild herbs.",
    latitude: 38.656,
    longitude: -7.904,
    mapX: 30,
    mapY: 65,
  },
];
